77 create user requires email
WildAid/o-fish-web pull request #272
Opened 2020-10-07 00:53 UTC by antwonthegreat

## Related Issue

Fixes #77 

## Checklist:

- [x ] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [x] I have commented on the linked issue
- [x] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [ ] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)

* **Optional: Add any explanations here** 

* **Optional: Add any relevant screenshots here**

2020-10-08 19:24 UTC, Sheeri requested changes
Hi @antwonthegreat ,

When I built this, the email field is indeed required in the same way that the agency role is. 

If I enter email first, the "create user" button becomes enabled, even if the "Role" field is not selected. If I then select the role, the create user button is still enabled.

If instead i first choose the Role field, the create user button becomes enabled. And then if I type something into Email, the "Create User" button becomes disabled again.

2020-10-08 19:47 UTC, antwonthegreat commented
> Hi @antwonthegreat ,
> 
> When I built this, the email field is indeed required in the same way that the agency role is.
> 
> If I enter email first, the "create user" button becomes enabled, even if the "Role" field is not selected. If I then select the role, the create user button is still enabled.
> 
> If instead i first choose the Role field, the create user button becomes enabled. And then if I type something into Email, the "Create User" button becomes disabled again.

Hi, I believe this is an existing bug with validation on this page. When I check out main if I select a role before any validation occurs (before focusing on any other fields), the Create User button never becomes enabled, even if the rest of the form is then filled out. Would you like me to try to address this on this branch as well?

2020-10-09 17:11 UTC, Sheeri commented
Hi @antwonthegreat - I have created issue #280 for that bug - comment there if you'd like to work on that one!

Will merge this one - Congratulations! 🎉 🙌 🎆 ㊗️  I really appreciate all the effort you put into the research (and code!) for this.

2020-10-09 17:11 UTC, Sheeri approved these changes

2020-10-09 17:11 UTC, merged