add dependencies to useEffect
WildAid/o-fish-web pull request #282
Opened 2020-10-10 14:27 UTC by fandok

## Related Issue

https://github.com/WildAid/o-fish-web/issues/278

Fixes #
add dependecies to useEffect

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [x] I have commented on the linked issue
- [x] I was assigned the linked issue (not required)
- [ ] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [ ] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)

* **Optional: Add any explanations here** 
the warning caused by the useEffect that has been implemented, not contains array of dependencies, so i add the dependencies based on the react's suggested.

to prevent any of this in the future, my advice is to add linter to check that. you can refer to it here https://reactjs.org/docs/hooks-rules.html

* **Optional: Add any relevant screenshots here**

2020-10-11 12:42 UTC, Sheeri requested changes
This has solved the issue - however, now the Agency Dashboard charts (at #/agency_charts/AGENCY_NAME) do not reload when the date picker at the top changes. Interestingly, the charts on the #/home page do reload when the date picker changes.

In order to fully test this, I will need to add charts to the sandbox server. I will do that tomorrow; if you have your own [build](https://wildaid.github.io/build/) with charts you can test it yourself. That is a few extra hours of work, though. It's up to you if you want to build your own instance, including charts, to test the bug, or if you want to wait.

2020-10-12 08:28 UTC, fandok commented
sorry i just check it @Sheeri can you build it? i can wait

2020-10-12 15:54 UTC, Sheeri commented
I built charts for the sandbox - While the dependencies you added stop the warning, you need ALL the dependencies in order for useEffect to properly reload the page when a filter changes:

[boxId, options.filter, options, filter, setFilter]

I have pushed this change, you can see it with https://github.com/WildAid/o-fish-web/pull/282/commits/ed7742fd3ed4b7ae7ce4c2554ce4ea45c97a1a62

(I will merge when the checks come out OK).

2020-10-12 15:54 UTC, Sheeri approved these changes

2020-10-12 15:56 UTC, merged

2020-10-12 15:56 UTC, Sheeri commented
Congratulations! 🎉 🙌 🎆 ㊗️ 

This PR is great and has been merged into the code. Thanks so much for contributing! If you'd like, you can request to work on another issue. We really appreciate your effort!

2020-10-19 17:54 UTC, Sheeri commented
Hi @fandok! 
We noticed you haven't claimed your digital MongoDB swag. To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.