Looked through the strings in the English translation to compare it t…
WildAid/o-fish-web pull request #323
Opened 2020-10-16 15:07 UTC by rh9891

…o the French translation making sure that the groupings were preserved. Inserted missing values into the translation file. Corrected grammatical errors. Those without a translation in the French were given the same value.

## Related Issue

Fixes #254 

## Checklist:

- [X] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [X] I linked an issue in the previous section
- [X] I have commented on the linked issue
- [X] I was assigned the linked issue (not required)
- [X] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [ ] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)

* **Optional: Add any explanations here** 

* **Optional: Add any relevant screenshots here**

2020-10-19 21:13 UTC, Sheeri requested changes
Hi @rh9891 - I love the changes you've made - I'm going to go through them in a bit more detail than I have already - making sure the spelling fixes you've done don't break other things (e.g. make sure changing "ELECTRINIC_SYSTEM" to "ELECTRONIC_SYSTEM" doesn't need to be done in the code also, since it's in the translations).

However, the primary ask was for a script, that would compare the localizations and add anything missing to the bottom of the file. I described it here: https://github.com/WildAid/o-fish-web/issues/254#issuecomment-707861383

I love that you also added the changes, and we will definitely merge them once I do some more testing....but for the issue itself, we need the script (so that we can run it periodically).

Thanks!

2020-10-20 01:16 UTC, Sheeri requested changes
Hi @rh9891,

I can see you put a LOT of work into this! It may seem like there are a lot of comments here, but that's because changing text can be fraught. 

For each change, I searched the code base for the string (e.g. 'LONGTITUDE') to see if the previous 'bad' variable was still used. In some cases, the 'bad' versions were, so I've noted what code should be updated.

I think the best way to proceed here would be to first fix the issues in this review of the PR. Then I can merge the PR. I will keep the referring issue open, and you can submit the script itself in a NEW pull request. (You absolutely deserve credit for 2 PR's given the amount of work you're putting in!)

Keep up the good work!

2020-10-20 01:16 UTC, Sheeri commented on src/helpers/i18n/en/translation.json
> +    "LOGGING_IN": "Logging in...",
Please also change in the referring file:
components/login/login.component.js

And in the Spanish translation:
src/helpers/i18n/es/translation.json

2020-10-20 01:16 UTC, Sheeri commented on src/helpers/i18n/fr/translation.json
> +    "SHARING_DATA_WITH": "{{agency}} informe {{sharingAgency}}",
This should be the translation of "Agencies sharing data with {{agency}}". (as above)

2020-10-20 16:54 UTC, rh9891 commented on src/helpers/i18n/en/translation.json
> +    "SHARING_DATA_WITH": "{{agency}} sharing data with {{sharingAgency}}",
I will be leaving this AS IS since the line was only changed up/down.

2020-10-22 16:58 UTC, Sheeri approved these changes

2020-10-22 16:59 UTC, Sheeri commented
Phew! Looks great, @rh9891 ! 

I will merge this but keep the original issue open - please open a new branch for a script that will do the comparison of strings/translations. thanks!

2020-10-22 16:59 UTC, merged