Fix #328: Update react-scripts dependency to 3.4.3 to resolve npm audit warning
WildAid/o-fish-web pull request #329
Opened 2020-10-17 20:15 UTC by stennie

## Related Issue

Fixes #328 

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [x] I have commented on the linked issue
- [ ] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

2020-10-17 20:19 UTC, stennie commented
The changelog for `react-scripts` indicates the only diffs between 3.4.1 and 3.4.3 were to address dependency warnings: https://github.com/facebook/create-react-app/blob/master/CHANGELOG.md

Both updates include the caveat:
> Note that this vulnerability did not affect Create React App projects, so this change is only necessary to satisfy auditing tools.

2020-10-20 02:33 UTC, Sheeri requested changes
Looks like there's still an audit warning even after that, and I see a lot more build warnings with this in place....

```
λ git diff
diff --git a/package.json b/package.json
index c2c784f..c8f6efd 100644
--- a/package.json
+++ b/package.json
@@ -30,7 +30,7 @@
     "react-router-config": "^5.1.1",
     "react-router-dom": "^5.1.2",
     "react-router-query-params": "^1.0.4",
-    "react-scripts": "3.4.1",
+    "react-scripts": "3.4.3",
     "react-world-flags": "^1.4.0",
     "typescript": "^3.7.0"
   },


λ npm install
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"10.15.3","npm":"6.14.6"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN react-flags-select@1.1.13 requires a peer of react@15.x but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.2 requires a peer of sass@^1.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.2 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.

removed 24 packages, updated 92 packages and audited 1778 packages in 42.732s

16 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

This has to do with object-path, which is currently at 0.11.4 but should be 0.11.5. I couldn't locate this in package.json - I tried a few incantations of adding it as a dependency, but to no avail.

I'm on the fence if I should merge this  as-is, since it technically fixes the audit warning about react-scripts....but I can also see the idea that this isn't really fixed until/unless all the npm audit warnings are gone.

I welcome your thoughts, @stennie ! (maybe merge this, but keep the original issue open?)

2020-10-22 16:52 UTC, Sheeri approved these changes

2020-10-22 16:53 UTC, merged

2020-10-22 16:53 UTC, Sheeri commented
Congratulations! 🎉 🙌 🎆 ㊗️ 

This PR is great and has been merged into the code. Thanks so much for contributing! If you'd like, you can request to work on another issue. We really appreciate your effort!